include $(APPDIR)/Make.defs

PROGNAME  = uart_flash
PRIORITY  = SCHED_PRIORITY_DEFAULT
STACKSIZE = 2048
MODULE    = $(CONFIG_EXAMPLES_UART_FLASH)

MAINSRC = uart_flash_main.c

include $(APPDIR)/Application.mk